### ISSUE TITLE
Running failed

### ISSUE THREAD

**Issue by aspergatus** [mstritt/orbit-image-analysis#4]
Hi Manuel

I were able to build the program with Gradle. But when I run it using the command you given, it shows me this error. Do you know what I have to change?

Best,
Tony
C:\Users\test\eclipse-workspace\orbit-image-analysis-3.08>java -XX:MaxPermSize=150m -Djavax.xml.parsers.DocumentBuilderFactory=com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderFactoryImpl -cp "build/libs/orbit-image-analysis-3.08.jar;build/libs/lib/*" com.actelion.research.orbit.imageAnalysis.components.OrbitImageAnalysis
Java HotSpot(TM) 64-Bit Server VM warning: Ignoring option MaxPermSize; support was removed in 8.0
02:44:36,418 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
02:44:36,419 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
02:44:36,420 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [jar:file:/C:/Users/test/eclipse-workspace/orbit-image-analysis-3.08/build/libs/orbit-image-analysis-3.08.jar!/logback.xml]
02:44:36,421 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs multiple times on the classpath.
02:44:36,421 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/C:/Users/test/eclipse-workspace/orbit-image-analysis-3.08/build/libs/orbit-image-analysis-3.08.jar!/logback.xml]
02:44:36,421 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/C:/Users/test/eclipse-workspace/orbit-image-analysis-3.08/build/libs/lib/image-provider-omero-1.5.10.jar!/logback.xml]
02:44:36,437 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@1ddf84b8 - URL [jar:file:/C:/Users/test/eclipse-workspace/orbit-image-analysis-3.08/build/libs/orbit-image-analysis-3.08.jar!/logback.xml] is not of type file
02:44:36,530 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
02:44:36,539 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
02:44:36,544 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
02:44:36,553 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
02:44:36,604 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [com.actelion.research.orbit.imageAnalysis.utils.OrbitLogAppender]
02:44:36,604 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [Orbit]
02:44:36,606 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
02:44:36,607 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.actelion.research] to INFO
02:44:36,607 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to WARN
02:44:36,607 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
02:44:36,608 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [Orbit] to Logger[ROOT]
02:44:36,608 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
02:44:36,609 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@1139b2f3 - Registering current configuration as safe fallback point

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at org.pushingpixels.substance.internal.utils.SubstanceColorUtilities.getDefaultBackgroundColor(SubstanceColorUtilities.java:759)
        at org.pushingpixels.substance.internal.utils.SubstanceColorUtilities.getBackgroundFillColor(SubstanceColorUtilities.java:661)
        at org.pushingpixels.substance.internal.ui.SubstancePanelUI.__org__pushingpixels__substance__internal__ui__SubstancePanelUI__installDefaults(SubstancePanelUI.java:74)
        at org.pushingpixels.substance.internal.ui.SubstancePanelUI.installDefaults(SubstancePanelUI.java)
        at java.desktop/javax.swing.plaf.basic.BasicPanelUI.installUI(BasicPanelUI.java:62)
        at org.pushingpixels.substance.internal.ui.SubstancePanelUI.__org__pushingpixels__substance__internal__ui__SubstancePanelUI__installUI(SubstancePanelUI.java)
        at org.pushingpixels.substance.internal.ui.SubstancePanelUI.installUI(SubstancePanelUI.java)
        at java.desktop/javax.swing.JComponent.setUI(JComponent.java:685)
        at java.desktop/javax.swing.JPanel.setUI(JPanel.java:150)
        at java.desktop/javax.swing.JPanel.updateUI(JPanel.java:126)
        at java.desktop/javax.swing.JPanel.<init>(JPanel.java:86)
        at java.desktop/javax.swing.JPanel.<init>(JPanel.java:109)
        at java.desktop/javax.swing.JPanel.<init>(JPanel.java:117)
        at java.desktop/javax.swing.JRootPane.createGlassPane(JRootPane.java:521)
        at java.desktop/javax.swing.JRootPane.<init>(JRootPane.java:348)
        at org.pushingpixels.flamingo.internal.ui.ribbon.JRibbonRootPane.<init>(JRibbonRootPane.java:55)
        at org.pushingpixels.flamingo.api.ribbon.JRibbonFrame.createRootPane(JRibbonFrame.java:552)
        at java.desktop/javax.swing.JFrame.frameInit(JFrame.java:258)
        at java.desktop/javax.swing.JFrame.<init>(JFrame.java:181)
        at org.pushingpixels.flamingo.api.ribbon.JRibbonFrame.<init>(JRibbonFrame.java:285)
        at com.actelion.research.orbit.imageAnalysis.components.OrbitImageAnalysis.<init>(OrbitImageAnalysis.java:251)
        at com.actelion.research.orbit.imageAnalysis.components.OrbitImageAnalysis.getInstance(OrbitImageAnalysis.java:2857)
        at com.actelion.research.orbit.imageAnalysis.components.OrbitImageAnalysis$15.run(OrbitImageAnalysis.java:2965)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:389)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by mstritt** [comment]
Hi Tony,
you have to run it with Java 8, Java 9+ is currently not supported.
Manuel

**Comment by aspergatus** [comment]
Hi Manuel,

You were right. I changed it to Java 8 and now it works beautifully.
Thanks!
Tony

**Comment by mstritt** [comment]
congrats, very cool!
Have fun with Orbit, and please let me know if you need anything else.
Manuel
